[package]
name = "ssufid_cli"
version = "0.1.0"
description.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
eyre = "0.6.12"
color-eyre = "0.6.3"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
time = { workspace = true, features = [
  "serde",
  "macros",
  "formatting",
  "parsing",
] }
futures = { workspace = true }
tokio = { workspace = true, features = ["full", "rt-multi-thread"] }
clap = { version = "4.5.36", features = ["derive"] }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "json"] }

ssufid = { workspace = true }
ssufid_common = { workspace = true }
ssufid_media = { workspace = true }
ssufid_mediamba = { workspace = true }
ssufid_ssucatch = { workspace = true }
ssufid_ssupath = { workspace = true }
ssufid_lifelongedu = { workspace = true }
ssufid_chemeng = { workspace = true }
ssufid_ee = { workspace = true }
ssufid_oasis = { workspace = true }
ssufid_startup = { workspace = true }
ssufid_ssfilm = { workspace = true }

[dev-dependencies]
time = { version = "0.3.40", features = ["macros"] }
