name: Crawl & Deploy

on:
  workflow_dispatch:

  # 테스트용
  pull_request:
    branches: [ "main" ]
  
  schedule:
    # this workflow triggers every day at 20:30 UTC (05:30 KST)
    - cron: "30 20 * * *"
jobs:
  daemon:
    runs-on: ubuntu-latest
    concurrency:
      group: daemon
      cancel-in-progress: true
    steps:
      # TODO: load .ssufid/cache dir

      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@nightly
      - name: Retrieve cargo cache
        uses: Leafwing-Studios/cargo-cache@v2
      - name: Cargo run
        run: cargo run
      
      - name: Clone to ssufid-sites repository
        uses: actions/checkout@v4
        with:
          path: ssufid-sites
          repository: yourssu/ssufid-sites
          ref: main
          token: ${{ secrets.SSUFID_SITES_GITHUB_TOKEN }}
      - name: Copy data and cache files
        run: |
          cp -r out/* ssufid-sites/
          mkdir -p ssufid-sites/.cache/ && cp -r .ssufid/cache/* ssufid-sites/.cache/
      - name: Push changes
        run: |
          cd ssufid-sites
          git config user.name "GitHub Actions"
          git config user.email ""
          git add .
          git commit -m "$(date +'%Y-%m-%d')"
          git push
